config/routes.rb
Rails.application.routes.draw do

  resources :payment_forms
  resources :sales
  post 'sales/persist'
  get 'sales/result'
  get 'integration_tests/show'
  get 'alarms/show'
  get 'statistics/show'
  get 'client_sales' => 'sales#client_sales'
  resources :users
  resources :clients
  resources :suppliers
  resources :products do
    resources :batches
  end
  resources :items
  root 'home#index'
  get 'login'   => 'login#show'
  post 'login'  => 'login#signin'
  get 'create_user_and_client' => 'home#create_user_and_client'
  get 'create_payment_form' => 'home#create_payment_form'
  get 'create_client' => 'home#create_client'
  get 'create_supplier' => 'home#create_supplier'
  get 'create_product' => 'home#create_product'
  get 'create_batch' => 'home#create_batch'
  get 'create_user' => 'home#create_user'
  get 'create_all' => 'home#create_all'
  get 'consume_batch_units' => 'home#consume_batch_units'

end

app/models/batch.rb
class Batch < ActiveRecord::Base
  belongs_to :product
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :sales

  def complete_name
    :"#{first_name.first}. #{last_name} #{dni}"
  end
end

app/models/dto.rb
class Dto < ActiveRecord::Base
abstract_class = true

end

app/models/item.rb
class Item < ActiveRecord::Base
	validates :name, :amount, :price, presence: true
end

app/models/payment_form.rb
class PaymentForm < ActiveRecord::Base
  has_many :vfps
  has_many :sales, through: :vfps
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :batches
  belongs_to :supplier
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  has_many :vfps
  has_many :payment_forms, :through => :vfps
  has_many :sale_details
  belongs_to :client
  belongs_to :user
end

app/models/sale_detail.rb
class SaleDetail < ActiveRecord::Base
  belongs_to :product
  belongs_to :sale
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/vfp.rb
class Vfp < ActiveRecord::Base
  belongs_to :sale
  belongs_to :payment_form
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:new]

  # GET /users
  # GET /users.json
  def index
    @users = UserService.all(session[:JSESSIONID])
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    @roles = [["Admin", "ROLE_ADMIN"], ["Empleado", "ROLE_EMPLOYEE"], ["Cliente", "ROLE_CLIENT"]]
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = UserService.save(user_params, session[:JSESSIONID])
    respond_to do |format|
      if @user.errors.empty?
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = UserService.find(params[:id], session[:JSESSIONID])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :role)
    end
end

app/helpers/alarms_helper.rb
module AlarmsHelper
end

app/helpers/batches_helper.rb
module BatchesHelper

	
end

app/helpers/clients_helper.rb
module ClientsHelper
	
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
	

	def self.find(id, j_session_id)
		response = HTTParty.get "http://localhost:8080/web-module/items/#{id}", cookies: {"JSESSIONID": j_session_id}
		Item.new (JSON.parse(response.body))
	end

	def self.save(item_params, j_session_id)
		options = {
			cookies: {"JSESSIONID": j_session_id},
			body: item_params.to_json,
			headers: { 'Content-Type' => 'application/json'}
		}
		item = Item.new(item_params)
		if item.valid?
			response = HTTParty.post "http://localhost:8080/web-module/items", options
			unless response.code==201 
				item.errors.add(:item, 'no se pudo guardar, codigo de respuesta '+ response.code.to_s)
			end
		end
		
		item
	end

	def self.all(j_session_id)
		response = HTTParty.get "http://localhost:8080/web-module/items", cookies: {"JSESSIONID": j_session_id}
		items_params = JSON.parse(response.body)
		
		items_params.map do |elem|
			Item.new(elem)
		end
		
	end

	def self.destroy(id,j_session_id)
		response = HTTParty.delete "http://localhost:8080/web-module/items/#{id}", cookies: {"JSESSIONID": j_session_id}
	end
	
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/products_helper.rb
module ProductsHelper

	

end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
	
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div class="card-panel purple lighten-2">
      <h5><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h5>

      <ul class="collection">
      <% @user.errors.full_messages.each do |message| %>
        <li class="collection-item"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <br>
  <div class="field">
    <%= f.label :rol %><br>

    <%= f.select(:role, @roles, {}, { :class =>"browser-default"}) %>
  </div>

   <br>
  <br>
  <button class="btn waves-effect waves-light" type="submit" name="action">Crear
    <i class="material-icons right">send</i>
  </button>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h3>Listado de usuarios</h3>
<a class="btn-floating btn-large waves-effect waves-light red" href="/users/new">
  <i class="material-icons">add</i>
</a>

<table class="striped">
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th>Rol</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Show', user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h3>Nuevo usuario</h3>

<%= render 'form' %>
<br>

<%= link_to 'Back', users_path, :class => "btn waves-effect waves-light" %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>