config/routes.rb
Rails.application.routes.draw do

  resources :payment_forms
  resources :sales
  post 'sales/persist'
  get 'sales/result'
  get 'integration_tests/show'
  get 'alarms/show'
  get 'statistics/show'
  get 'client_sales' => 'sales#client_sales'
  resources :users
  resources :clients
  resources :suppliers
  resources :products do
    resources :batches
  end
  resources :items
  root 'home#index'
  get 'login'   => 'login#show'
  post 'login'  => 'login#signin'
  get 'create_user_and_client' => 'home#create_user_and_client'
  get 'create_payment_form' => 'home#create_payment_form'
  get 'create_client' => 'home#create_client'
  get 'create_supplier' => 'home#create_supplier'
  get 'create_product' => 'home#create_product'
  get 'create_batch' => 'home#create_batch'
  get 'create_user' => 'home#create_user'
  get 'create_all' => 'home#create_all'
  get 'consume_batch_units' => 'home#consume_batch_units'

end

app/models/batch.rb
class Batch < ActiveRecord::Base
  belongs_to :product
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :sales

  def complete_name
    :"#{first_name.first}. #{last_name} #{dni}"
  end
end

app/models/dto.rb
class Dto < ActiveRecord::Base
abstract_class = true

end

app/models/item.rb
class Item < ActiveRecord::Base
	validates :name, :amount, :price, presence: true
end

app/models/payment_form.rb
class PaymentForm < ActiveRecord::Base
  has_many :vfps
  has_many :sales, through: :vfps
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :batches
  belongs_to :supplier
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  has_many :vfps
  has_many :payment_forms, :through => :vfps
  has_many :sale_details
  belongs_to :client
  belongs_to :user
end

app/models/sale_detail.rb
class SaleDetail < ActiveRecord::Base
  belongs_to :product
  belongs_to :sale
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/vfp.rb
class Vfp < ActiveRecord::Base
  belongs_to :sale
  belongs_to :payment_form
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:new]

  # GET /items
  # GET /items.json
  def index
    @items = ItemsHelper.all(session[:JSESSIONID])
  end

  # GET /items/1
  # GET /items/1.json
  def show

  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create

    @item = ItemsHelper.save(item_params, session[:JSESSIONID])
    respond_to do |format|
      if @item.errors.empty?
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    
    ItemsHelper.destroy(params[:id], session[:JSESSIONID])
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = ItemsHelper.find(params[:id], session[:JSESSIONID])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :amount, :price)
    end
end

app/helpers/alarms_helper.rb
module AlarmsHelper
end

app/helpers/batches_helper.rb
module BatchesHelper

	
end

app/helpers/clients_helper.rb
module ClientsHelper
	
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
	

	def self.find(id, j_session_id)
		response = HTTParty.get "http://localhost:8080/web-module/items/#{id}", cookies: {"JSESSIONID": j_session_id}
		Item.new (JSON.parse(response.body))
	end

	def self.save(item_params, j_session_id)
		options = {
			cookies: {"JSESSIONID": j_session_id},
			body: item_params.to_json,
			headers: { 'Content-Type' => 'application/json'}
		}
		item = Item.new(item_params)
		if item.valid?
			response = HTTParty.post "http://localhost:8080/web-module/items", options
			unless response.code==201 
				item.errors.add(:item, 'no se pudo guardar, codigo de respuesta '+ response.code.to_s)
			end
		end
		
		item
	end

	def self.all(j_session_id)
		response = HTTParty.get "http://localhost:8080/web-module/items", cookies: {"JSESSIONID": j_session_id}
		items_params = JSON.parse(response.body)
		
		items_params.map do |elem|
			Item.new(elem)
		end
		
	end

	def self.destroy(id,j_session_id)
		response = HTTParty.delete "http://localhost:8080/web-module/items/#{id}", cookies: {"JSESSIONID": j_session_id}
	end
	
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/products_helper.rb
module ProductsHelper

	

end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
	
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Amount</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.amount %></td>
        <td><%= item.price %></td>
        <td><%= link_to 'Show', item_path(item) %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item_path(item), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @item.amount %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>