config/routes.rb
Rails.application.routes.draw do

  resources :payment_forms
  resources :sales
  post 'sales/persist'
  get 'sales/result'
  get 'integration_tests/show'
  get 'alarms/show'
  get 'statistics/show'
  get 'client_sales' => 'sales#client_sales'
  resources :users
  resources :clients
  resources :suppliers
  resources :products do
    resources :batches
  end
  resources :items
  root 'home#index'
  get 'login'   => 'login#show'
  post 'login'  => 'login#signin'
  get 'create_user_and_client' => 'home#create_user_and_client'
  get 'create_payment_form' => 'home#create_payment_form'
  get 'create_client' => 'home#create_client'
  get 'create_supplier' => 'home#create_supplier'
  get 'create_product' => 'home#create_product'
  get 'create_batch' => 'home#create_batch'
  get 'create_user' => 'home#create_user'
  get 'create_all' => 'home#create_all'
  get 'consume_batch_units' => 'home#consume_batch_units'

end

app/models/batch.rb
class Batch < ActiveRecord::Base
  belongs_to :product
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :sales

  def complete_name
    :"#{first_name.first}. #{last_name} #{dni}"
  end
end

app/models/dto.rb
class Dto < ActiveRecord::Base
abstract_class = true

end

app/models/item.rb
class Item < ActiveRecord::Base
	validates :name, :amount, :price, presence: true
end

app/models/payment_form.rb
class PaymentForm < ActiveRecord::Base
  has_many :vfps
  has_many :sales, through: :vfps
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :batches
  belongs_to :supplier
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  has_many :vfps
  has_many :payment_forms, :through => :vfps
  has_many :sale_details
  belongs_to :client
  belongs_to :user
end

app/models/sale_detail.rb
class SaleDetail < ActiveRecord::Base
  belongs_to :product
  belongs_to :sale
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/vfp.rb
class Vfp < ActiveRecord::Base
  belongs_to :sale
  belongs_to :payment_form
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:new]

  # GET /products
  # GET /products.json
  def index
    @products = ProductService.all(session[:JSESSIONID])
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @batches = BatchService.all(@product, session[:JSESSIONID])
  end

  # GET /products/new
  def new
    @product = Product.new
    @suppliers = SupplierService.all(session[:JSESSIONID]) || []
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = ProductService.save(product_params, session[:JSESSIONID])
    respond_to do |format|
      if @product.errors.empty?
        format.html { redirect_to @product, notice: 'Producto creado exitosamente.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    ProductService.destroy(params[:id], session[:JSESSIONID])
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = ProductService.find(params[:id], session[:JSESSIONID])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    # , :batch_id --- acordarse de permitir en el futuro el batch_id
    params.require(:product).permit(:name, :minimum, :amount, :supplier_id, :price)
  end
end

app/helpers/alarms_helper.rb
module AlarmsHelper
end

app/helpers/batches_helper.rb
module BatchesHelper

	
end

app/helpers/clients_helper.rb
module ClientsHelper
	
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
	

	def self.find(id, j_session_id)
		response = HTTParty.get "http://localhost:8080/web-module/items/#{id}", cookies: {"JSESSIONID": j_session_id}
		Item.new (JSON.parse(response.body))
	end

	def self.save(item_params, j_session_id)
		options = {
			cookies: {"JSESSIONID": j_session_id},
			body: item_params.to_json,
			headers: { 'Content-Type' => 'application/json'}
		}
		item = Item.new(item_params)
		if item.valid?
			response = HTTParty.post "http://localhost:8080/web-module/items", options
			unless response.code==201 
				item.errors.add(:item, 'no se pudo guardar, codigo de respuesta '+ response.code.to_s)
			end
		end
		
		item
	end

	def self.all(j_session_id)
		response = HTTParty.get "http://localhost:8080/web-module/items", cookies: {"JSESSIONID": j_session_id}
		items_params = JSON.parse(response.body)
		
		items_params.map do |elem|
			Item.new(elem)
		end
		
	end

	def self.destroy(id,j_session_id)
		response = HTTParty.delete "http://localhost:8080/web-module/items/#{id}", cookies: {"JSESSIONID": j_session_id}
	end
	
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/products_helper.rb
module ProductsHelper

	

end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
	
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
    <% if @product.errors.any? %>
        <div class="card-panel purple lighten-2">
          <h5><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h5>

          <ul class="collection">
            <% @product.errors.full_messages.each do |message| %>
                <li class="collection-item"><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name, :required => true %>
    </div>

    <div class="field">
      <%= f.label "unidades minimas para la activacion de alarma:" %><br>
      <%= f.number_field :minimum, :required => true %>
    </div>

    <div class="field">
      <%= f.label "Proveedor: " %>
      <%= collection_select(:product, :supplier_id, @suppliers, :id, :name, {}, class: "browser-default", required: true) %>
    </div>

    <div class="field">
      <%= f.label "Precio: " %>
      <%= f.number_field :price, :required => true %>
    </div>

    <br><br>
    <button class="btn waves-effect waves-light" type="submit" name="action">Crear
      <i class="material-icons right">send</i>
    </button>

<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h3>Listado de productos</h3>

<a class="btn-floating btn-large waves-effect waves-light red" href="/products/new">
  <i class="material-icons">add</i>
</a>
<table class="striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Cant de alarma</th>
      <th>Cant actual</th>
      <th> $ precio</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.minimum %></td>
        <td><%= product.amount %></td>
        <td><%= product.price %></td></tx>
        
        <td><%= link_to 'Detalles', product_path(product)  %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/products/new.html.erb
<h3>Nuevo producto</h3>

<%= render 'form' %>

<br>
<%= link_to 'Back', products_path, :class => "btn waves-effect waves-light"%>

app/views/products/show.html.erb
<h3> <%= @product.name %></h3>




<h5>Proveedor:  <%= @product.supplier.name %></h5>
<p>
  <strong>Activar alarma por debajo de: <%= @product.minimum %> unidades</strong>
  
</p>

<p>
  <strong>Cantidad actual:</strong>
  <%= @product.amount %>
</p>
<br>



<h4>Lotes:</h4>

<a class="btn-floating btn-large waves-effect waves-light red" href=<%= new_product_batch_url(@product) %>>
  <i class="material-icons">add</i>
</a>

<table class="striped">
  <thead>
    <tr>
      <th>Detalle</th>
      <th>Unidades restantes</th>
      <th>Unidades totales</th>
      <th>Fecha de entrada</th>
      <th>Fecha de vencimiento</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

   <tbody>
    <% @batches.each do |batch| %>
      <tr>
        <td><%= batch.detail %></td>
        <td><%= batch.remaining_units %></td>
        <td><%= batch.total_units %></td>
        <td><%= batch.entry_date %></td>
        <td><%= batch.expiration_date %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Back', products_path, :class =>"btn waves-effect waves-light" %>
<br><br>

 