config/routes.rb
Rails.application.routes.draw do

  resources :payment_forms
  resources :sales
  post 'sales/persist'
  get 'sales/result'
  get 'integration_tests/show'
  get 'alarms/show'
  get 'statistics/show'
  get 'client_sales' => 'sales#client_sales'
  resources :users
  resources :clients
  resources :suppliers
  resources :products do
    resources :batches
  end
  resources :items
  root 'home#index'
  get 'login'   => 'login#show'
  post 'login'  => 'login#signin'
  get 'create_user_and_client' => 'home#create_user_and_client'
  get 'create_payment_form' => 'home#create_payment_form'
  get 'create_client' => 'home#create_client'
  get 'create_supplier' => 'home#create_supplier'
  get 'create_product' => 'home#create_product'
  get 'create_batch' => 'home#create_batch'
  get 'create_user' => 'home#create_user'
  get 'create_all' => 'home#create_all'
  get 'consume_batch_units' => 'home#consume_batch_units'

end

app/models/batch.rb
class Batch < ActiveRecord::Base
  belongs_to :product
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :sales

  def complete_name
    :"#{first_name.first}. #{last_name} #{dni}"
  end
end

app/models/dto.rb
class Dto < ActiveRecord::Base
abstract_class = true

end

app/models/item.rb
class Item < ActiveRecord::Base
	validates :name, :amount, :price, presence: true
end

app/models/payment_form.rb
class PaymentForm < ActiveRecord::Base
  has_many :vfps
  has_many :sales, through: :vfps
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :batches
  belongs_to :supplier
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  has_many :vfps
  has_many :payment_forms, :through => :vfps
  has_many :sale_details
  belongs_to :client
  belongs_to :user
end

app/models/sale_detail.rb
class SaleDetail < ActiveRecord::Base
  belongs_to :product
  belongs_to :sale
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/vfp.rb
class Vfp < ActiveRecord::Base
  belongs_to :sale
  belongs_to :payment_form
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_service
  before_action :set_sale, only: [:show, :update, :destroy]
  before_action :set_persist_model, only: [:persist]
  skip_before_action :require_login, only: [:new]

  def set_service
    @saleService = SaleService.new(session[:JSESSIONID])
    @paymentService = PaymentFormService.new(session[:JSESSIONID])
  end

  # GET /sales
  # GET /sales.json
  def index
    @sales = @saleService.all_to_json().as_json;
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  def client_sales
    if session[:role] == 'ROLE_ADMIN'
      render :index
    else
      @sales_json = @saleService.all_client_sales(session[:client_id])
    end
  end

  # GET /sales/new
  def new
    @sale = Sale.new
    @payment_forms = @paymentService.all || []
    @clients = ClientService.all(session[:JSESSIONID]) || []
  end

  # GET /sales/1/edit
  def edit
    str = '{"fecha":"2015-01-01","nro":"123","cliente":{"id": "2"},"detalles":[{"cantidad":"20","fila": 1,"producto": {"id": "1"}}],"precio":"10","formasPago":[{"cantidad": 1,"formaPago":{"id":"1"}}]}'
    @saleService.test str
  end

  def persist
    p = set_persist_model
    sale = Sale.new
    sale.fecha = Date.strptime(p['fecha'], '%y-%m-%d')
    sale.sale_details = Array.new

    p['productos'].to_h.each_with_index do |(k, v), i|
      detail = SaleDetail.new
      detail.cantidad = v['cantidad'];
      detail.fila = i
      detail.precio = v['precio']
      detail.product_id = v['product_id']
      sale.sale_details<<detail
    end

    sale.vfps = Array.new
    p['formasPago'].to_h.each_with_index do |(k, v), i|
      vfp = Vfp.new
      vfp.cantidad = v['cantidad']
      vfp.payment_form_id = v['id']
      sale.vfps << vfp
    end

    sale.client = Client.new id: p['client_id']
    possibleErrors = @saleService.save_fromjson sale, include: [:sale_details, :vfps]

    if possibleErrors.blank?
      flash[:notice] = 'La venta Se Generó correctamente'
      render :json => 'todo OK'.to_json
    else
      render :json => possibleErrors.to_json
    end

  end

  # POST /sales
  # POST /sales.json
  def create


  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update

  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_sale
    if !params['id'].blank?
      @sale = @saleService.find_json(params['id'])
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def sale_params
    params.require(:sale).permit(:fecha)
  end

  def set_persist_model
    params.require(:sale).permit(:fecha, :client_id, {:formasPago => [:id, :cantidad]}, {:productos => [:product_id, :cantidad, :precio]})
  end
end

app/helpers/alarms_helper.rb
module AlarmsHelper
end

app/helpers/batches_helper.rb
module BatchesHelper

	
end

app/helpers/clients_helper.rb
module ClientsHelper
	
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
	

	def self.find(id, j_session_id)
		response = HTTParty.get "http://localhost:8080/web-module/items/#{id}", cookies: {"JSESSIONID": j_session_id}
		Item.new (JSON.parse(response.body))
	end

	def self.save(item_params, j_session_id)
		options = {
			cookies: {"JSESSIONID": j_session_id},
			body: item_params.to_json,
			headers: { 'Content-Type' => 'application/json'}
		}
		item = Item.new(item_params)
		if item.valid?
			response = HTTParty.post "http://localhost:8080/web-module/items", options
			unless response.code==201 
				item.errors.add(:item, 'no se pudo guardar, codigo de respuesta '+ response.code.to_s)
			end
		end
		
		item
	end

	def self.all(j_session_id)
		response = HTTParty.get "http://localhost:8080/web-module/items", cookies: {"JSESSIONID": j_session_id}
		items_params = JSON.parse(response.body)
		
		items_params.map do |elem|
			Item.new(elem)
		end
		
	end

	def self.destroy(id,j_session_id)
		response = HTTParty.delete "http://localhost:8080/web-module/items/#{id}", cookies: {"JSESSIONID": j_session_id}
	end
	
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/products_helper.rb
module ProductsHelper

	

end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
	
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
    <% if @sale.errors.any? %>
        <div class="section">
          <div id="error_explanation">
            <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

            <ul>
              <% @sale.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>

    <div class="input-field">
      <select name=cliente" data-bind="options: clientesActuales,
                            optionsText: function(i) {return i.first_name +' '+i.last_name},
                            value: clienteSeleccionado,
                            optionsCaption: 'Seleccione...'" required>
      </select>
      <%= f.label 'Cliente a facturar: ' %>

    </div>
    <br>
    <div class="row">
      <div class="col s9 m9 l9 input-field">
        <select name="payments" data-bind="options: pagosActuales,
                            optionsText: function(i) {return i.nombre},
                            value: pagoSeleccionado,
                            optionsCaption: 'Seleccione...'" required>
        </select>
        <%= f.label 'Forma de Pago ' %>
      </div>
      <div class="input-field col s3 m3 l3">
        <%= label :cantidad, 'cantidad' %>
        <%= number_field :cantidad, 'cantidad',{'data-bind':'value: cantidadFormaPago'} %>
      </div>
    </div>
    <br>
    <button data-target="modal1" class="btn-floating modal-trigger"><i class="material-icons dp48">queue</i>
    </button>
    <table>
      <thead>
      <th>código</th>
      <th>nombre</th>
      <th>precio U.</th>
      <th>cantidad</th>
      <th>precio t.</th>
      <th></th>
      </thead>
      <tbody data-bind="foreach: productos">
      <tr>
        <td data-bind="text: codigo"></td>
        <td data-bind="text: nombre"></td>
        <td data-bind="text: price"></td>
        <td data-bind="text: cantidad"></td>
        <td data-bind="text: total"></td>
        <td data-bind="visible: codigo() != null">
          <button class="btn-floating" data-bind="click: deleteRow"><i class="material-icons">delete</i>
          </button>
        </td>
      </tr>
      </tbody>
      <tfoot>
      <tr>
        <td colspan="4"></td>
        <td>Total: $ <span data-bind="text:Total"></span></td>
      </tr>
      <tr>
        <td colspan="4"></td>
        <td data-bind="visible: parseFloat(Vuelto()) >= 0">Vuelto: $ <span data-bind="text:Vuelto"></span></td>
      </tr>
      </tfoot>
    </table>



    <div id="modal1" class="modal">
      <div class="modal-content">
        <h4>Agregar un producto</h4>
        <div class="input-field">
          <%= label_tag 'cantidad' %>
          <%= number_field :producto, :cantidad, {class: 'input-field validate', 'data-bind': 'value: cantidad', 'required': ''} %>
        </div>
        <div class="input-field col s12">
          <select data-bind="options: productosActuales,
                            optionsText: function(i) {return i.name},
                            value: productoSeleccionado,
                            optionsCaption: 'Seleccione...'" required>
          </select>
          <label>Productos</label>

        </div>
      </div>
      <div class="modal-footer">
        <a data-bind="click: AgregarProducto" class=" modal-action waves-effect waves-green btn-flat">Agregar</a>
      </div>
    </div>

    <%= link_to 'TERMINAR', '#', {class: "btn waves-effect waves-light", 'data-bind': 'click: Persist'} %>
    <%= link_to 'Cancelar', sales_path, :class => "btn waves-effect waves-light" %>
<% end %>

app/views/sales/client_sales.html.erb
<p id="notice"><%= notice %></p>

<h1>Ventas</h1>
<table class="striped">
  <thead>
  <tr>
    <th>id</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @sales_json.each do |sale| %>
      <tr>
        <td><%= sale['id'] %></td>
        <td>
          <a href="/sales/<%= sale['id'] %>" class="btn-floating btn-small waves-effect waves-light red"><i class="material-icons dp48">picture_in_picture</i></a>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<% unless flash[:notice].blank? %>
    <p id="notice"><%= flash[:notice] %></p>
<% end %>
<h1>Ventas</h1>

<%= link_to new_sale_path, {class: 'btn-floating btn-large waves-effect waves-light red'} do %>
    <%= content_tag :i, 'add', {class: 'material-icons'} %>
<% end %>

<table>
  <thead>
  <tr>
    <th>facturas</th>
  </tr>
  </thead>
  <tbody data-bind="foreach: ventas">
  <tr>
    <td data-bind="click: $parent.ver.bind($data, id()) ">
      <button class="btn-floating btn-small waves-effect waves-light red">
        <i class="material-icons dp48">picture_in_picture</i></button>
    </td>
  </tr>
  </tbody>
</table>


<script>
  $(document).ready(function () {
    var vm = {
      ventas: '1',
      ver: '1'
    };
    vm.ventas = ko.observableArray([])
    vm.ver = function (id) {
      window.location = '/sales/' + id;
    };
    $.get('/sales.json').done(function (data) {
      ko.mapping.fromJS(data, {}, vm.ventas)
    });
    ko.applyBindings(vm);
  })
</script>

app/views/sales/new.html.erb
<h1>Nueva Venta</h1>
<div style="display:none" class="card-panel purple lighten-2" data-bind="visible: errors().length > 0 " id="error_explanation">
  <h5>Error al guardar la factura</h5>
  <ul class="collection" data-bind="foreach: errors">
    <li class="collection-item" data-bind="text: $data"></li>
  </ul>
</div>

<%= render 'form' %>


<script>
  $(document).ready(function () {
    var vm;
    $('select').material_select();
    $('.datepicker').pickadate();
    $('.collapsible').collapsible();
    $('.modal-trigger').leanModal({
      ready: function () {
        $('select').material_select();
        //vm.productoSeleccionado(undefined);
        vm.cantidad(null);
        vm.precio(null);
      }
    })

    var LineaTabla = function (codigo, nombre, cantidad, precio) {
      this.codigo = ko.observable(codigo); //id
      this.nombre = ko.observable(nombre);
      this.cantidad = ko.observable(parseInt(cantidad));
      this.price = ko.observable(parseFloat(precio));
      var self = this;
      this.total = ko.computed(function () {
        return parseFloat(self.cantidad()) * parseFloat(self.price());
      });

      this.deleteRow = function () {
        vm.productos.remove(this);
      };

      this.unmap = function () {
        return {
          cantidad: ko.toJS(this.cantidad),
          precio: ko.toJS(this.price),
          product_id: ko.toJS(this.codigo)
        }
      }
    };

    var LineaPagos = function (nombre, cantidad, id) {
      this.nombre = ko.observable(nombre);
      this.cantidad = ko.observable(parseFloat(cantidad));
      this.id = ko.observable(id);
      this.deleteRow = function () {
        vm.pagos.remove(this);
      };
      this.unmap = function () {
        return {
          cantidad: ko.toJS(this.cantidad),
          id: ko.toJS(this.id)
        }
      }
    };

    var f = function () {
      if (vm.productoSeleccionado() == null || vm.cantidad() <= 0) {
        Materialize.toast("Todos los campos son obligatorios");
        return;
      }

      var c = vm.productoSeleccionado().id;
      var n = vm.productoSeleccionado().name;
      var precio = parseFloat(vm.productoSeleccionado().price);
      var d = vm.productos().filter(function (a) {
        return a.codigo() == vm.productoSeleccionado().id
      });

      if (d.length == 0) {
        var p = new LineaTabla(c, n, vm.cantidad(), precio);
        vm.productos.push(p);
        vm.productos.notifySubscribers();
        Materialize.toast('Se agregó un producto a la lista', 4000);
      } else {
        d[0].cantidad(parseInt(d[0].cantidad()) + parseInt(vm.cantidad()));
        vm.productos.notifySubscribers();
        Materialize.toast('Se actualizó la cantidad', 4000);
      }

      $("#modal1").closeModal();
    }

    var p = function () {
      if (vm.pagoSeleccionado() == null || vm.precio() <= 0) {
        Materialize.toast('Todos los campos son obligatorios', 4000);
        return;
      }
      var pay = new LineaPagos(vm.pagoSeleccionado().nombre, vm.precio(), vm.pagoSeleccionado().id);
      vm.pagos.push(pay);
      vm.pagos.notifySubscribers();
      Materialize.toast('Se agregó una forma de pago', 4000);
      $("#modal2").closeModal();
    };

    vm = {
      productos: ko.observableArray([]),
      pagos: ko.observableArray([]),
      cantidad: ko.observable(0),
      precio: ko.observable(0),
      cantidadFormaPago: ko.observable(0),
      productoSeleccionado: ko.observable(),
      pagoSeleccionado: ko.observable(null),
      clienteSeleccionado: ko.observable(null),
      fechaHoy: ko.observable(Date.today().format("d  M, Y")),
      AgregarProducto: f,
      AgregarPago: p
    };

    vm.Total = ko.computed(function () {
      var p = 0;
      var mapp = vm.productos().map(function (c) {
        return parseFloat(c.total());
      });
      if (mapp.length) {
        p = mapp.reduce(function (n, p) {
          return n + p;
        });
      }

      return parseFloat(p.toFixed(2));
    });

    vm.Restante = ko.computed(function () {
      var r = 0;

      return parseFloat((vm.Total() - parseFloat(vm.cantidadFormaPago())).toFixed(2));
    });

    vm.Vuelto = ko.computed(function () {
      return -vm.Restante();
    });

    vm.PagoTotal = ko.computed(function () {
      var r = 0;
      var mapp = vm.pagos().map(function (c) {
        return parseFloat(c.cantidad());
      });

      if (mapp.length) {
        r = mapp.reduce(function (n, r) {
          return n + r;
        })
      }

      return parseFloat(r.toFixed(2));
    });

    $.when($.ajax('/products.json'),
        $.ajax('/clients.json'),
        $.ajax('/payment_forms.json'))
        .then(function (d1, d2, d3) {
          var prods = d1[0];
          var clientes = d2[0];
          var pagos = d3[0];
          vm.productosActuales = ko.observableArray(prods);
          vm.clientesActuales = ko.observableArray(clientes);
          vm.pagosActuales = ko.observableArray(pagos);
          vm.errors = ko.observableArray([])
          ko.applyBindings(vm)
          $('select').material_select();
        });
    var validate = function () {
      var valid = true;
      //if (!$('#new_sale')[0].checkValidity()) {
      //valid = false;
      //}
      //if (vm.Restante() > 0) {
      //  valid = false;
      //}

      if (vm.productos().length == 0) {
        valid = false;
        Materialize.toast('Debe haber al menos un productos', 4000);
      }

      if (vm.clienteSeleccionado() == null) {
        Materialize.toast('Debe haber al menos un cliente seleccionado', 4000);
        valid = false;
      }

      if (vm.pagoSeleccionado() == null) {
        Materialize.toast('Debe haber al menos un pago seleccionado', 4000);
        valid = false;
      }

      if (vm.Total() > vm.cantidadFormaPago()) {
        Materialize.toast('No alcanza a cubrir el pago total', 4000);
        valid = false;
      }

      return valid;
    };
    vm.Persist = function () {
      //validar todo en front. cd

      if (validate()) {
        var plainSale = {
          fecha: Date.today().format("y-m-d"),
          client_id: vm.clienteSeleccionado() != null && vm.clienteSeleccionado() != undefined ? vm.clienteSeleccionado().id : 0,
          productos: vm.productos().map(function (e) {
            return e.unmap()
          }),
          formasPago: [{
            cantidad: vm.cantidadFormaPago(), id: vm.pagoSeleccionado().id
          }],
          authenticity_token: $("[name=authenticity_token]").val()
        }
        $.ajax(
            {
              url: "/sales/persist",
              dataType: 'json',
              method: 'POST',
              data: {sale: plainSale}
            }
        ).done(function (d) {
          if ($.isArray(d.messageErrors) && d.messageErrors.length) {
            ko.mapping.fromJS(d.messageErrors, {}, vm.errors);
          } else {
            window.location = '/sales'
          }
        }).error(function () {

        }).always(function () {

        });

      }
    }
  })

</script>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>
<br>
Fecha: <%= @sale['fecha'] %>
<br>
cliente: <%= @sale['client']['first_name'] %> <%= @sale['client']['last_name'] %>
<br>
<table>
  <thead>
  <tr>
    <th>fila</th>
    <th>cantidad</th>
    <th>Nombre</th>
    <th>precio T.</th>
  </tr>
  </thead>
  <tbody>
  <% @sale['sale_details'].to_a.each do |v| %>
      <tr>
        <td><%= v['fila'] %></td>
        <td><%= v['cantidad'] %></td>
        <td><%= v['product']['name'] %></td>
        <td><%= v['precio'] %></td>
      </tr>
  <% end %>
  </tbody>
  <tfoot>
  <tr>
    <td colspan="2"></td>
    <td>
      Total:
    </td>
    <td>
      $ <%= @sale['sale_details'].to_a.inject(0) { |a, b| a + b['precio'] } %>
    </td>
  </tr>
  <% @sale['payment_forms'].to_a.each do |v| %>
      <tr>
        <td colspan="2"></td>
        <td> <strong><%= v['payment_form']['nombre'] %></strong> Pago</td>
        <td>
          $ <%= v['payment_form']['cantidad'] || 0 %>
        </td>
      </tr>
  <% end %>
  </tfoot>
</table>
<br>
<%= link_to 'Back', client_sales_url, :class => "btn waves-effect waves-light" %>